#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Сбор реальных UI-строк из игры в словарь XUnity.AutoTranslator.

XUnity.AutoTranslator записывает все встреченные в игре строки в
`BepInEx/Translation/ru/Text/_AutoGeneratedTranslations.txt` форматом
`original=translation`. Это вспомогательный инструмент, который:

  * читает этот файл из папки игры;
  * отбрасывает строки, уже присутствующие в словаре (по `original`);
  * выводит НОВЫЕ строки для перевода в `mod_ui/harvest_candidates.txt`
    форматом `original=` (пустой перевод нужно заполнить);
  * при `--merge` вливает заполненный файл кандидатов обратно в словарь
    (добавляет только отсутствующие `original`, байт-в-байт сохраняя ключ).

Использование:
  python3 tools/harvest_ui.py                 # собрать новые строки в кандидаты
  # (заполнить переводы в mod_ui/harvest_candidates.txt)
  python3 tools/harvest_ui.py --merge         # влить заполненные кандидаты в словарь

Формат файла кандидатов: одна строка на запись `original=перевод`, комментарии
`#` и пустые строки игнорируются. Уже имеющиеся в словаре `original` при merge
не перезаписываются (словарь — источник истины для существующего).

Пути к игре берутся из окружения (см. tools/_paths.py), по умолчанию —
текущие пути автора.
"""
import os
import sys

from _paths import GAME, OUT

DICT = os.path.join(OUT, "mod_ui", "BepInEx", "Translation", "ru", "Text", "ui_dictionary.txt")
CANDIDATES = os.path.join(OUT, "mod_ui", "harvest_candidates.txt")
AUTOGEN = os.path.join(GAME, "BepInEx", "Translation", "ru", "Text", "_AutoGeneratedTranslations.txt")


def load_dictionary_originals(path):
    """Вернуть set «original» из словаря (всё слева от первого '=')."""
    originals = set()
    if not os.path.exists(path):
        return originals
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                originals.add(line.split("=", 1)[0])
    return originals


def load_autogen(path):
    """Прочитать _AutoGeneratedTranslations.txt -> список (original, translation)."""
    entries = []
    if not os.path.exists(path):
        return entries
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                orig, trans = line.split("=", 1)
                entries.append((orig, trans))
    return entries


def load_candidates(path):
    """Прочитать файл кандидатов -> список (original, translation)."""
    entries = []
    if not os.path.exists(path):
        return entries
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                orig, trans = line.split("=", 1)
                entries.append((orig, trans))
    return entries


def harvest():
    known = load_dictionary_originals(DICT)
    autogen = load_autogen(AUTOGEN)

    # Собираем уникальные новые original, в порядке первого появления.
    seen = set()
    new_items = []  # (original, hint)
    for orig, trans in autogen:
        if orig in known or orig in seen:
            continue
        seen.add(orig)
        hint = "" if (trans == orig or trans.strip() == "") else trans
        new_items.append((orig, hint))

    with open(CANDIDATES, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Собранные из игры UI-строки, которых нет в словаре.\n")
        f.write("# Заполни перевод после '=' и запусти: python3 tools/harvest_ui.py --merge\n")
        f.write("# '#'-комментарии и пустые строки игнорируются.\n\n")
        for orig, hint in new_items:
            f.write(orig + "=" + hint + "\n")

    print(f"Встречено в игре: {len(autogen)} строк")
    print(f"Уже в словаре: {len(autogen) - len(new_items)}")
    print(f"НОВЫХ строк для перевода: {len(new_items)}")
    print(f"Кандидаты записаны: {CANDIDATES}")
    if not os.path.exists(AUTOGEN):
        print("\n[!] _AutoGeneratedTranslations.txt пока не создан — поиграй и открой нужные")
        print("    экраны (карта/журнал/задачи/инвентарь/настройки), затем повтори.")
    return new_items


def merge():
    known = load_dictionary_originals(DICT)
    candidates = load_candidates(CANDIDATES)

    added = []
    with open(DICT, "a", encoding="utf-8", newline="\n") as f:
        for orig, trans in candidates:
            if orig in known:
                continue
            if trans.strip() == "":
                continue  # не заполнено — пропускаем
            # двойной перенос строки перед новым блоком для читаемости
            f.write("\n" + orig + "=" + trans + "\n")
            known.add(orig)
            added.append((orig, trans))

    print(f"Кандидатов: {len(candidates)}, добавлено в словарь: {len(added)}")
    for orig, trans in added:
        print(f"  + {orig} = {trans}")
    if added:
        print(f"\nСловарь обновлён: {DICT}")
        print("Не забудь скопировать его в игру и нажать ALT+R.")
    else:
        print("Новых строк не добавлено (нет заполненных кандидатов или всё уже в словаре).")


def main():
    args = sys.argv[1:]
    if "--merge" in args:
        merge()
    else:
        harvest()


if __name__ == "__main__":
    main()
